"""
read_binary_logs.py
python read_binary_logs.py meesho_partitions\meesho-order-server_ERROR.bin
------------------------------------------------------------
MEESHO BINARY LOG READER

Reads binary partition files generated by
log_harvester_daemon.py and converts them back into
human-readable logs.

Usage:

python read_binary_logs.py meesho_partitions/meesho-order-server_ERROR.bin
"""

import struct
import sys
import os

# ==========================================================
# Binary Log Level Mapping
# ==========================================================

LEVEL_CODES = {
    "DEBUG": 0,
    "INFO": 1,
    "WARNING": 2,
    "ERROR": 3
}

CODE_LEVELS = {
    value: key
    for key, value in LEVEL_CODES.items()
}

# ==========================================================
# Read Binary Records
# ==========================================================

def read_binary_records(file_path):

    with open(file_path, "rb") as binary_file:
        data = binary_file.read()

    offset = 0

    decoded_logs = []

    while offset < len(data):

        # --------------------------------------------------
        # Read Record Length
        # --------------------------------------------------

        (record_length,) = struct.unpack_from(
            "!I",
            data,
            offset
        )

        offset += 4

        record = data[offset: offset + record_length]

        offset += record_length

        # --------------------------------------------------
        # Decode Header
        # --------------------------------------------------

        timestamp_bytes, level_byte, service_length = struct.unpack_from(
            "!19sBH",
            record,
            0
        )

        position = 22

        service_name = record[
            position:
            position + service_length
        ].decode("utf-8")

        position += service_length

        (message_length,) = struct.unpack_from(
            "!H",
            record,
            position
        )

        position += 2

        message = record[
            position:
            position + message_length
        ].decode("utf-8")

        decoded_logs.append({

            "timestamp":
                timestamp_bytes.decode("ascii").strip(),

            "level":
                CODE_LEVELS[level_byte],

            "service":
                service_name,

            "message":
                message

        })

    return decoded_logs


# ==========================================================
# Main
# ==========================================================

if __name__ == "__main__":

    if len(sys.argv) != 2:

        print("\nUsage:")

        print(
            "python read_binary_logs.py "
            "<path_to_binary_file>\n"
        )

        print("Example:")

        print(
            "python read_binary_logs.py "
            "meesho_partitions/meesho-order-server_ERROR.bin\n"
        )

        sys.exit(1)

    file_path = sys.argv[1]

    if not os.path.exists(file_path):

        print(f"\nFile Not Found : {file_path}")

        sys.exit(1)

    logs = read_binary_records(file_path)

    print("\n" + "=" * 75)
    print("             MEESHO BINARY LOG READER")
    print("=" * 75)

    print(f"\nPartition File : {file_path}")

    print(f"Total Records  : {len(logs)}")

    print("-" * 75)

    for index, log in enumerate(logs, start=1):

        print(f"\nRecord {index}")

        print(f"Timestamp : {log['timestamp']}")

        print(f"Level     : {log['level']}")

        print(f"Server    : {log['service']}")

        print(f"Message   : {log['message']}")

    print("\n" + "=" * 75)
    print("End of Records")
    print("=" * 75)